Redux hooks on chat/active-messenger with tests
ita-social-projects/horondi_client_fe pull request #1139
Opened 2021-10-26 18:51 UTC by Vlodkojr

- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅All tests passed locally
- [x] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [x] 🔗 Link pull request to issue

2021-11-01 08:51 UTC, maarekua commented on src/containers/chat/active-messenger/tests/active-messenger.spec.js
> +    wrapper.unmount();
We only need to unmount if we have something to test on unmount.

2021-11-05 09:49 UTC, BohdanShchur requested changes

2021-11-05 09:49 UTC, BohdanShchur commented on src/containers/chat/active-messenger/tests/active-messenger.spec.js
>      );
What we expect in test? Fix this code smell. Add some expect method like toBe(), toEqual() ...

2021-11-05 15:48 UTC, vasyaukr commented on jest.config.js
> +    '\\.(css|scss)$': 'identity-obj-proxy',
why u change configs if the main purpose to refactor redux?

2021-11-08 15:30 UTC, ElitKondor approved these changes

2021-11-08 15:54 UTC, Skrekliam approved these changes

2021-11-08 15:54 UTC, merged