Feature/1150/your order component
ita-social-projects/horondi_client_fe pull request #1209
Opened 2021-11-07 22:56 UTC by boris-giga

## Description
created new component YourOrder

#### Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** original screenshot ** | ** updated screenshot ** |

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-11-15 11:53 UTC, maarekua requested changes

2021-11-15 11:53 UTC, maarekua commented on src/containers/checkout/checkout-form/checkout-form.styles.js
> +    // '&:hover': {
Remove commented.

2021-11-15 15:10 UTC, boris-giga commented on src/containers/checkout/checkout-form/checkout-form.styles.js
> +    // '&:hover': {
done

2021-11-15 16:32 UTC, AnastasiaKhukhra approved these changes

2021-11-16 10:38 UTC, Skrekliam approved these changes

2021-11-16 10:38 UTC, merged