Fixed white underline that appears with dark theme
ita-social-projects/horondi_client_fe pull request #1248
Opened 2021-11-11 17:27 UTC by rostyslaw27

## Description

Fixed white underline that appears with dark theme when you hover into the currency or language icon

#### Screenshots

 Original:  
 ![image](https://user-images.githubusercontent.com/57355852/141340813-197beb79-39f3-4d6b-bd97-997fe0f9c494.png) 

 Updated
 ![image](https://user-images.githubusercontent.com/57355852/141341141-78be7511-cb6d-46a5-b4c5-8db96ca3e826.png)

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-11-12 08:54 UTC, maarekua requested changes

2021-11-12 08:54 UTC, maarekua commented on src/containers/currency/currency.styles.js
> +      borderBottomColor: '#0000 !important'
Try to remove important!

2021-11-12 17:59 UTC, rostyslaw27 commented on src/containers/currency/currency.styles.js
> +      borderBottomColor: '#0000 !important'
fixed

2021-11-15 11:10 UTC, maarekua approved these changes

2021-11-16 07:33 UTC, boris-giga approved these changes

2021-11-17 07:06 UTC, olga-gchak approved these changes

2021-11-17 07:06 UTC, merged