Refactor/1301/products theme
ita-social-projects/horondi_client_fe pull request #1302
Opened 2021-11-16 14:36 UTC by romanortynskyi

## Description
Removed ThemeContext from products

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-11-17 08:30 UTC, maarekua submitted a review, later dismissed

2021-11-17 11:20 UTC, Skrekliam requested changes

2021-11-19 08:31 UTC, maarekua approved these changes

2021-11-19 08:47 UTC, Skrekliam commented
Please add screenshot of console. It should be clear.

2021-11-19 11:16 UTC, closed without merging