wishlist redesign
ita-social-projects/horondi_client_fe pull request #1328
Opened 2021-11-18 20:55 UTC by tarasSanotskyi

## Description
Redesign wishlist page according to the new design on FE 

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-11-18 21:25 UTC, Skrekliam requested changes

2021-11-18 21:25 UTC, Skrekliam commented on src/components/modal/modal.styles.js
> +    // backgroundColor: theme.palette.background.paper,
Please remove comment

2021-11-18 21:25 UTC, Skrekliam commented on src/components/modal/modal.styles.js
> +      // fontColor: theme.palette.black,
Remove comment

2021-11-19 08:24 UTC, maarekua requested changes

2021-11-19 08:24 UTC, maarekua commented on src/components/modal/modal.js
> +import closeIcon from '../../images/modal-icon/modalCloseIcon.svg';
Use material icons.

2021-11-19 08:46 UTC, Skrekliam commented
Please add screenshot of console. It should be clear.

2021-11-23 11:10 UTC, tarasSanotskyi commented on src/components/modal/modal.styles.js
> +    // backgroundColor: theme.palette.background.paper,
done

2021-11-23 11:10 UTC, tarasSanotskyi commented on src/components/modal/modal.styles.js
> +      // fontColor: theme.palette.black,
done

2021-11-23 11:11 UTC, tarasSanotskyi commented on src/components/modal/modal.js
> +import closeIcon from '../../images/modal-icon/modalCloseIcon.svg';
done

2021-11-23 12:29 UTC, Skrekliam commented on src/components/modal/tests/modal.spec.js
> +    );
Why you dont use this in beforeEach?

2021-11-23 13:16 UTC, tarasSanotskyi commented on src/components/modal/tests/modal.spec.js
> +    );
fixed

2021-11-23 18:32 UTC, bohdanst1914 approved these changes

2021-11-23 19:14 UTC, Skrekliam approved these changes

2021-11-23 19:14 UTC, merged