Chat email fe
ita-social-projects/horondi_client_fe pull request #191
Opened 2020-09-18 16:56 UTC by TarasKun

-implementing sending emails from chat on front end
-add sagas
-add snack bar

2020-09-20 18:22 UTC, DmytroDidukh requested changes

2020-09-20 18:22 UTC, DmytroDidukh commented on src/containers/chat/active-messenger/active-messenger.js
> +import { sendEmail } from '../../../redux/chat/chat.actions';
please separate imports: first from libraries, then local data

2020-09-20 19:38 UTC, DmytroDidukh approved these changes

2020-09-23 17:13 UTC, TorskyM approved these changes

2020-09-23 17:13 UTC, merged