Bugfix/1890/inexpedient pagination after searching througth search field
ita-social-projects/horondi_client_fe pull request #1934
Opened 2022-05-11 11:40 UTC by Pipuss

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

#### Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** original screenshot ** | ** updated screenshot ** |

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-05-13 07:22 UTC, Pipuss commented on src/hooks/use-product-filters/use-product-filters.js
>      if (target.checked) {
// todo 
refactor this

2022-05-13 07:26 UTC, maarekua requested changes

2022-05-13 07:26 UTC, maarekua commented on src/pages/product-list-page/product-sort/product-sort.js
> +    debounce((value) => {
Remove debounce. Use clearTimeout

2022-05-13 07:26 UTC, maarekua commented on src/pages/product-list-page/product-list-filter/hot-item-filter/hot-item-filter.js
> +    setHotItem(!!searchParams.get(isHotItemFilter));
Check

2022-05-20 07:18 UTC, maarekua approved these changes

2022-05-21 07:33 UTC, Yevhendzyuba approved these changes

2022-05-21 07:34 UTC, merged