Improvement/2022/home search clear icon
ita-social-projects/horondi_client_fe pull request #2032
Opened 2022-06-24 14:37 UTC by Tolik170

## Description

Add an icon which clear search field in home page

#### Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ![before](https://user-images.githubusercontent.com/63456632/175555944-494a2810-8aa0-4566-9d47-be6dee7e819f.png)|  ![after](https://user-images.githubusercontent.com/63456632/175555497-55ff702e-876e-40f9-a2ad-bd511a6d9cf9.png) |

### Checklist

- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅All tests passed locally
- [x] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [x] 🔗 Link pull request to issue

2022-06-25 10:00 UTC, maarekua requested changes

2022-06-25 10:00 UTC, maarekua commented on src/containers/search-bar/ClearIcon.js
> +        <>
Redundant <>.

2022-06-25 10:00 UTC, maarekua commented on src/containers/search-bar/search-bar.js
> +      <SearchIcon searchInputIcon={styles.searchInputIcon} />
https://mui.com/material-ui/api/input-adornment/#main-content

2022-06-26 13:14 UTC, Tolik170 commented on src/containers/search-bar/ClearIcon.js
> +        <>
reworked.

2022-06-26 13:14 UTC, Tolik170 commented on src/containers/search-bar/search-bar.js
> +      <SearchIcon searchInputIcon={styles.searchInputIcon} />
reworked.

2022-06-27 12:37 UTC, closed without merging