Created pop up after clicking on gift certificate icon
ita-social-projects/horondi_client_fe pull request #2134
Opened 2022-09-16 08:56 UTC by MickhaelSh

## Description
Created pop up after clicking on gift certificate icon
#### Screenshots

![giftcertificate](https://user-images.githubusercontent.com/97129041/190598795-ffa630bf-3fb7-486c-9f40-089179aac9b5.png)

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-09-16 15:32 UTC, Tolik170 requested changes

2022-09-16 15:32 UTC, Tolik170 commented on src/containers/modal-gift-certificate/tests/modal-gift-certificate.spec.js
> +    act(() => {
i think you don't need act to wrap fireEvent
https://testing-library.com/docs/example-input-event

2022-09-16 15:32 UTC, Tolik170 commented on src/pages/gift-certificate/operations/gift-certificate.mutations.js
> +  mutation ($id: ID!, $email: String!, $oldEmail: String!, $language: Int!) {
maybe better create a type or use existing one

2022-09-16 15:32 UTC, Tolik170 commented on src/containers/modal-gift-certificate/modal-gift-certificate.js
> +              <Loader heightWrap='25px' height='20px' width='20px' />
better move it to styles

2022-09-16 15:32 UTC, Tolik170 commented on src/components/confirm-dialog/confirm-dialog.styles.js
> +    color: '#808080',
use closeModalIcon from palette

2022-09-16 15:32 UTC, Tolik170 commented on src/components/confirm-dialog/confirm-dialog.styles.js
> +    borderBottom: '2px solid #E2E8F0',
use titleBorder from palette

2022-09-16 15:32 UTC, Tolik170 commented on src/components/confirm-dialog/confirm-dialog.js
> +      <div className={styles.paper} data-cy='removing-modal'>
i don't see that you use this data-cy in tests.

2022-09-18 11:05 UTC, dmytruk-y approved these changes

2022-09-18 11:09 UTC, Tolik170 submitted a review, later dismissed

2022-09-18 13:02 UTC, dmytruk-y approved these changes

2022-09-18 13:11 UTC, Tolik170 approved these changes

2022-09-18 13:57 UTC, merged