expanded useCart hook
ita-social-projects/horondi_client_fe pull request #2194
Opened 2022-10-28 17:27 UTC by MickhaelSh

expanded useCart hook

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-10-28 17:38 UTC, Pipuss requested changes

2022-10-28 17:38 UTC, Pipuss commented on src/containers/orders/cart/filled-cart/filled-cart.js
> +                  disabled={!!(certificateData || promoCode)}
Use Boolean() instead !!

2022-10-28 17:38 UTC, Pipuss commented on src/containers/orders/order/your-order/your-order.js
> +          ? cartItems.map((item) => (
Bad practice using arr.map() inside jsx

2022-10-28 18:45 UTC, MickhaelSh commented on src/containers/orders/cart/filled-cart/filled-cart.js
> +                  disabled={!!(certificateData || promoCode)}
fixed

2022-10-28 18:45 UTC, MickhaelSh commented on src/containers/orders/order/your-order/your-order.js
> +          ? cartItems.map((item) => (
fixed

2022-10-29 09:23 UTC, Pipuss approved these changes

2022-10-29 11:52 UTC, Tolik170 approved these changes

2022-10-31 08:25 UTC, maarekua approved these changes

2022-10-31 09:07 UTC, merged