redirect to choosen category
ita-social-projects/horondi_client_fe pull request #2223
Opened 2022-11-08 11:49 UTC by Yurenko

## Description

When selecting a category, it redirects to the catalog without the selected category and shows all products

#### Screenshots

![Знімок екрана 2022-11-03 145723](https://user-images.githubusercontent.com/83120263/200555916-cc34eaba-7991-481f-a7b1-9ae38e93cb80.jpg)

Before 
![Знімок екрана 2022-11-08 134637](https://user-images.githubusercontent.com/83120263/200556235-f2475358-405e-437b-b4a3-04dd0092ddb4.jpg)

After
![Знімок екрана 2022-11-08 134657](https://user-images.githubusercontent.com/83120263/200556260-43a935db-74d1-4059-ac90-28989480e444.jpg)

### Checklist

- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅All tests passed locally
- [x] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [x] 🔗 Link pull request to issue

2022-11-08 15:19 UTC, Tolik170 submitted a review, later dismissed

2022-11-08 20:52 UTC, Pipuss approved these changes

2022-11-09 11:33 UTC, maarekua requested changes

2022-11-09 11:33 UTC, maarekua commented on src/pages/product-details/product-path/product-path.js
> +        to={`${pathToCategory}?&${URL_QUERIES_NAME.page}=${URL_QUERIES_NAME.defaultPage}&${countPerPage}=${countPerPageValue}&${URL_QUERIES_NAME.categoryFilter}=%2C${categoryId}`}
Move to const, and then use in JSX.

2022-11-10 09:20 UTC, Yurenko commented on src/pages/product-details/product-path/product-path.js
> +        to={`${pathToCategory}?&${URL_QUERIES_NAME.page}=${URL_QUERIES_NAME.defaultPage}&${countPerPage}=${countPerPageValue}&${URL_QUERIES_NAME.categoryFilter}=%2C${categoryId}`}
Fixed

2022-11-11 13:05 UTC, maarekua approved these changes

2022-11-14 08:24 UTC, Tolik170 approved these changes

2022-11-14 08:24 UTC, IrynaMel approved these changes

2022-11-14 08:25 UTC, merged