add dependencies in useEffect
ita-social-projects/horondi_client_fe pull request #2253
Opened 2022-11-18 11:41 UTC by IrynaMel

## Description

fix quantity in cart
#### Screenshots

### Checklist

- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅All tests passed locally
- [x] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [x] 🔗 Link pull request to issue

2022-11-18 12:00 UTC, tarasSanotskyi approved these changes

2022-11-18 12:06 UTC, Pipuss submitted a review, later dismissed

2022-11-18 15:39 UTC, MickhaelSh submitted a review, later dismissed

2022-11-21 08:24 UTC, byavdoshniak requested changes

2022-11-21 08:24 UTC, byavdoshniak commented on src/containers/orders/cart/cart-item/cart-item.js
> +  const debounceQuantity = useDebounce(inputValue, 200);
revert to 500ms

2022-11-22 13:44 UTC, IrynaMel commented on src/containers/orders/cart/cart-item/cart-item.js
> +  const debounceQuantity = useDebounce(inputValue, 200);
fixed

2022-11-22 16:56 UTC, MickhaelSh submitted a review, later dismissed

2022-11-23 08:44 UTC, tarasSanotskyi approved these changes

2022-11-23 09:00 UTC, tarasSanotskyi approved these changes

2022-11-23 09:05 UTC, MickhaelSh approved these changes

2022-11-23 11:10 UTC, byavdoshniak approved these changes

2022-11-23 13:04 UTC, merged