Bugfix/2269/currency language theme does not exist on mobile
ita-social-projects/horondi_client_fe pull request #2278
Opened 2022-11-25 10:40 UTC by Tolik170

## Description

1) Fixed language, curreny, theme block styles on mobile at sidebar
2) Fixed color of facebook and instagram icons while changing theme to dark at sidebar

#### Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ![image](https://user-images.githubusercontent.com/63456632/203964644-fadd7c5d-0717-4a44-87b5-4618c302faa0.png)| ![image](https://user-images.githubusercontent.com/63456632/203964765-a50efa5c-ab0d-4215-8d21-335a1bcef3e9.png)|

### Checklist

- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅All tests passed locally
- [x] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [x] 🔗 Link pull request to issue

2022-11-25 11:10 UTC, Pipuss approved these changes

2022-11-25 11:11 UTC, MickhaelSh approved these changes

2022-11-25 11:13 UTC, tarasSanotskyi commented on src/containers/sidebar/sidebar.js
> +          color={isLightTheme[0] ? '#000000' : '#FFFFFF'}
use colors from palette

2022-11-25 11:35 UTC, Tolik170 commented on src/containers/sidebar/sidebar.js
> +          color={isLightTheme[0] ? '#000000' : '#FFFFFF'}
done.

2022-11-25 11:40 UTC, MickhaelSh approved these changes

2022-11-25 11:50 UTC, LubomyrKashuba approved these changes

2022-11-25 11:58 UTC, MickhaelSh approved these changes

2022-11-25 11:59 UTC, IrynaMel approved these changes

2022-11-25 12:05 UTC, Pipuss approved these changes

2022-11-25 12:13 UTC, tarasSanotskyi submitted a review, later dismissed

2022-11-25 14:19 UTC, byavdoshniak approved these changes

2022-11-25 14:20 UTC, LubomyrKashuba requested changes

2022-11-25 14:20 UTC, LubomyrKashuba commented on src/containers/sidemenu-right-bar/sidemenu-right-bar.styles.js
> +    transform: 'scale(1.1)',
use fontSize

2022-11-25 15:14 UTC, Tolik170 commented on src/containers/sidemenu-right-bar/sidemenu-right-bar.styles.js
> +    transform: 'scale(1.1)',
Fixed.

2022-11-26 14:31 UTC, LubomyrKashuba approved these changes

2022-11-28 07:52 UTC, Yurenko approved these changes

2022-11-28 07:55 UTC, MickhaelSh approved these changes

2022-11-28 07:57 UTC, IrynaMel approved these changes

2022-11-28 17:18 UTC, olga-gchak approved these changes

2022-11-28 18:14 UTC, merged