add price notification for cart
ita-social-projects/horondi_client_fe pull request #2375
Opened 2022-12-22 19:04 UTC by Yevhendzyuba

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

#### Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** original screenshot ** | ** updated screenshot ** |

### Checklist

- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2022-12-22 21:33 UTC, KhrystynaPavlikovska approved these changes

2022-12-22 22:17 UTC, MickhaelSh requested changes
give more css to this message, it should not stretch the whole block,  and currency sigh should match the price size

2022-12-23 08:45 UTC, KhrystynaPavlikovska approved these changes

2022-12-23 12:12 UTC, Roman-Peretiatko approved these changes

2022-12-28 09:56 UTC, closed without merging