Save filled data on checkout and fill checkout with authorized user's data
ita-social-projects/horondi_client_fe pull request #638
Opened 2021-04-08 11:56 UTC by dmytro07

### Checklist
- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-04-09 11:44 UTC, yuliiakucher submitted a review, later dismissed

2021-04-09 20:52 UTC, twihell commented on src/utils/checkout.js
> +const COURIER = 'COURIER';
Is it ok if we have magic strings within util files? Even if it's not regulated strictly, there is still **consts/** folder, so maybe it's better to move this const there.

2021-04-09 20:53 UTC, twihell commented on src/utils/checkout.js
> +export const RESET = 'reset';
Same here

2021-04-09 21:11 UTC, twihell commented on src/configs/index.js
> +export const HORONDI = 'horondi';
you can use this const in  **src/index.js**  in localStorage/sesstionStorage conditionals

2021-04-10 17:34 UTC, grebiniuk requested changes
Try to fix warehouses for NovaPoshta on checkout.

2021-04-12 10:17 UTC, twihell approved these changes

2021-04-12 22:55 UTC, grebiniuk approved these changes
Well done!

2021-04-13 16:31 UTC, yuliiakucher approved these changes

2021-04-13 16:31 UTC, merged