Eslintrc fix
ita-social-projects/horondi_client_fe pull request #693
Opened 2021-06-07 07:31 UTC by Meamzy

Installed prettier-eslint-config

In order to apply fix, you'll need to use 'npm install' on your local environment.

### Checklist
- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-06-07 13:09 UTC, YuriiDubnytskyi approved these changes

2021-06-07 13:43 UTC, YuriiDubnytskyi requested changes

2021-06-07 13:43 UTC, YuriiDubnytskyi commented on .prettierrc
> -  "tabWidth": 2,
Why did you delete this? Is it will work?

2021-06-08 06:08 UTC, sergklukvin requested changes
![Без імені](https://user-images.githubusercontent.com/76059218/121131857-0b1be280-c839-11eb-82ef-95287978e376.jpg)

Why was the lock.json package changed?

2021-06-08 06:09 UTC, sergklukvin requested changes
![Без імені1](https://user-images.githubusercontent.com/76059218/121131918-22f36680-c839-11eb-99c3-2ff552028925.jpg)

Prettier isn't correct

2021-06-11 11:21 UTC, closed without merging

2021-06-11 11:22 UTC, Meamzy commented
Going to do some checks, thx for reviews.