Bug fix/734
ita-social-projects/horondi_client_fe pull request #739
Opened 2021-06-15 16:27 UTC by mvmoshchovskyi

Fixed page create yourself after DB refactoring 

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

#### Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

### Checklist
- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-06-15 18:59 UTC, grebiniuk requested changes

2021-06-15 18:59 UTC, grebiniuk commented on src/pages/images-constructor/hooks.js
> +      dispatch(getConstructorBottom(currentModel.eligibleOptions.constructorBottom[0]._id));
Please use destructoring
![image](https://user-images.githubusercontent.com/32039216/122108414-13b18180-ce14-11eb-9d3e-9a70fa38a109.png)

2021-06-15 19:23 UTC, mvmoshchovskyi commented on src/pages/images-constructor/hooks.js
> +      dispatch(getConstructorBottom(currentModel.eligibleOptions.constructorBottom[0]._id));
added destructoring

2021-06-15 19:26 UTC, grebiniuk approved these changes

2021-06-16 05:25 UTC, sergklukvin approved these changes

2021-06-16 05:26 UTC, merged