OrderHistory Component
ita-social-projects/horondi_client_fe pull request #742
Opened 2021-06-16 14:19 UTC by sergklukvin

![1](https://user-images.githubusercontent.com/76059218/122235794-a7438a80-cec6-11eb-8cd1-ec6ee3858752.jpg)
![2](https://user-images.githubusercontent.com/76059218/122235867-b4f91000-cec6-11eb-86a7-f85e60c4e201.jpg)
![3](https://user-images.githubusercontent.com/76059218/122235889-b88c9700-cec6-11eb-9e52-3add802e0d86.jpg)
![4](https://user-images.githubusercontent.com/76059218/122235908-bb878780-cec6-11eb-912b-4e26afc8d09f.jpg)

### Checklist
- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-06-22 19:19 UTC, yuliiakucher commented on src/containers/orders/order-history/order-history-pagination/order-history-pagination.js
> +        variant='outlined'
please remove magic string

2021-06-22 19:20 UTC, yuliiakucher commented on src/pages/product-list-page/product-list-page.js
> +    console.log(e);
please remove console.log

2021-06-22 19:21 UTC, yuliiakucher commented on src/pages/product-list-page/product-list-page.js
> +    console.log(searchParams.toString());
same

2021-06-23 10:43 UTC, grebiniuk requested changes

2021-06-23 10:43 UTC, grebiniuk commented on src/containers/orders/order-history/order-history-order/order-history-order.js
> +                {`${orderStatus[0].toUpperCase()}${orderStatus.slice(1)}`}
Please use _.capitalize() https://lodash.com/docs/#capitalize

2021-06-23 10:43 UTC, grebiniuk commented on src/containers/orders/order-history/order-history-pagination/order-history-pagination.js
> +        page={currentPage + 1}
Please consider the other way of showing the page number

2021-06-23 10:43 UTC, grebiniuk commented on src/pages/order-history/order-history.js
> +    dispatch(setCurrentPage(value - 1));
the same

2021-06-23 18:23 UTC, Elugormo requested changes

2021-06-23 18:23 UTC, Elugormo commented on src/containers/orders/order-history/order-history-order-item/order-history-order-item.js
> +            {(data.fixedPrice[currency].value / 100).toFixed()}{' '}
Please create utility function for expression and fix whitespace by replacing it with {'\u00A0'}

2021-06-23 18:23 UTC, Elugormo commented on src/containers/orders/order-history/order-history-order/order-history-order.js
> +  const handleClick = () => {
Change naming of function to a more specific one.

2021-06-23 18:23 UTC, Elugormo commented on src/containers/orders/order-history/order-history-order/order-history-order.js
> +  for (let i = 0; i < quantityImg; i++) {
Use map function instead of for( let ) loops.

2021-06-23 18:23 UTC, Elugormo commented on src/containers/orders/order-history/order-history-order/order-history-order.js
> +  const totalPrice = (order.totalItemsPrice[currency].value / 100).toFixed(0);
Use the same utility function to evaluate expressions as we commented above.

2021-06-23 18:23 UTC, Elugormo commented on src/containers/orders/order-history/order-history-order/order-history-order.js
> +                {totalPrice} <FontAwesomeIcon icon={currencySign} />
Add Unicode whitespace symbol (like the one we commented previously &nbsp)

2021-06-23 22:31 UTC, grebiniuk approved these changes

2021-06-24 07:45 UTC, yuliiakucher approved these changes

2021-06-24 07:47 UTC, Elugormo approved these changes

2021-06-24 08:13 UTC, YuriiDubnytskyi approved these changes

2021-06-24 08:13 UTC, merged