Fix/608
ita-social-projects/horondi_client_fe pull request #746
Opened 2021-06-18 12:08 UTC by AndronShermeta

Fixed Filters, products pagination and sort

#### Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/73708298/122558225-843fe480-d046-11eb-9ec7-355a5affebdc.png) |  ![image](https://user-images.githubusercontent.com/73708298/122558279-928e0080-d046-11eb-8332-dfb7af64fed4.png)

![image](https://user-images.githubusercontent.com/73708298/122558304-9b7ed200-d046-11eb-89ad-e9583f7be909.png) |
![image](https://user-images.githubusercontent.com/73708298/122558336-a2a5e000-d046-11eb-81ca-303fe9885a9e.png)

![image](https://user-images.githubusercontent.com/73708298/122558480-cbc67080-d046-11eb-9135-cf726d5d930e.png) |
![image](https://user-images.githubusercontent.com/73708298/122558538-dda81380-d046-11eb-8219-cf0cc8060432.png)

### Checklist
- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-06-22 18:03 UTC, yuliiakucher commented
![image](https://user-images.githubusercontent.com/61886864/122976571-2dffd800-d39d-11eb-909c-1f0e578503c6.png)
please highlight the selected button

2021-06-22 18:19 UTC, yuliiakucher commented on src/pages/product-list-page/product-sort/product-sort.js
> +          dispatch(setSortByPrice(optionValue.value+2));
please change the value in const from -1 to 1

2021-06-22 18:24 UTC, yuliiakucher commented on src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
> +        max={max+1}
please remove +1 a

2021-06-22 19:43 UTC, grebiniuk requested changes

2021-06-22 19:43 UTC, grebiniuk commented on src/redux/products/products.reducer.js
> +        currentPage: action.payload - 1
Please fix in the other way

2021-06-23 17:53 UTC, Elugormo requested changes

2021-06-23 17:53 UTC, Elugormo commented on src/pages/product-list-page/count-per-page/count-per-page.js
> +  console.log(searchParams.get("countPerPage"))
remove console.log

2021-06-23 17:53 UTC, Elugormo commented on src/pages/product-list-page/product-list-filter/price-filter/price-filter.js
> +  const max = parseInt(maxPrice ? maxPrice[currency].value / 100 : 1000, 10);
Create utility function for these cases

2021-06-23 17:53 UTC, Elugormo commented on src/redux/products/tests/products.reducer.test.js
> +  it('should set current page to 3', () => {
fix "it" description

2021-06-23 19:00 UTC, grebiniuk requested changes

2021-06-23 19:00 UTC, grebiniuk commented on src/utils/priceCalculating.js
> +export const min = (minPrice,currency) => parseInt(minPrice ? minPrice[currency].value / 100 : 0, 10);
You should make a new fucntion, like:

const roundPrice = (price) => parseInt(price/100, 10)
And use it in min/max functions and not duplicate the code.

2021-06-23 22:07 UTC, grebiniuk requested changes

2021-06-23 22:07 UTC, grebiniuk commented on src/utils/priceCalculating.js
> +const roundPrice = (price) => parseInt(price/100, 10)
Where is the semicolon?

2021-06-24 11:08 UTC, grebiniuk requested changes
Please fix conflicts

2021-06-24 11:47 UTC, grebiniuk approved these changes

2021-06-24 11:51 UTC, yuliiakucher approved these changes

2021-06-24 12:30 UTC, Elugormo approved these changes

2021-06-24 12:31 UTC, merged