Modified active-messenger component, fix mutation, added tests
ita-social-projects/horondi_client_fe pull request #798
Opened 2021-07-08 15:50 UTC by Mabonik

## Description

- Added error on the empty body;
- Fixed problem with sending (GraphQL);
- Added firstName and email autocomplete for authorized users. Also, users can change data there;
- Field for the message can change size due to the text.

#### Screenshots

**Original**    
<img width="340" alt="befor4" src="https://user-images.githubusercontent.com/61788391/124952611-11aa9f00-e01d-11eb-84e8-4134f2b161f7.png">
 **Updated**
<img width="340" alt="after1" src="https://user-images.githubusercontent.com/61788391/124952755-2d15aa00-e01d-11eb-9f9f-08d8929b212c.png"> <img width="340" alt="after2" src="https://user-images.githubusercontent.com/61788391/124952693-1ec78e00-e01d-11eb-9752-2e39ae471371.png">

### Checklist
- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-07-08 16:19 UTC, mvmoshchovskyi submitted a review, later dismissed

2021-07-16 15:08 UTC, sergklukvin requested changes
![2](https://user-images.githubusercontent.com/76059218/125968845-f3db843b-887e-4c52-81c5-3c6405519cfd.jpg)
1. Delete coma
2.  Message have to  be  "Поле повинно містити від 2 до 500 символів"

2021-07-16 19:50 UTC, sergklukvin approved these changes

2021-07-19 11:52 UTC, mvmoshchovskyi approved these changes

2021-07-19 11:52 UTC, merged