Bugfix/663 Password recovery
ita-social-projects/horondi_client_fe pull request #802
Opened 2021-07-08 21:15 UTC by Serhii-Ahafonov

The bug was fixed. Token is being received.

![image](https://user-images.githubusercontent.com/61708033/124991651-99f36900-e04a-11eb-8489-32633ff0b582.png)

### Checklist
- [ ] 🔽 My branch is up-to-date with "development" branch
- [ ] ✅All tests passed locally
- [ ] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [ ] 🔗 Link pull request to issue

2021-07-08 21:23 UTC, Elugormo commented
Resolve code smell, please

2021-07-16 14:37 UTC, Wasya1212 requested changes
Need to check RegExp again

2021-07-20 17:58 UTC, Wasya1212 approved these changes

2021-07-20 18:00 UTC, VolodymyrStyk approved these changes

2021-07-20 18:00 UTC, merged